server:
  port: 80
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everytime?characterEncoding=UTF-8
    username: root
    password: root
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB